Repository APP-iOS2/final-zipadoo, pull requests merged in 2024-01, with the labels that each got.

#401 위치 허용
  Zipadoo/Zipadoo.xcodeproj/project.pbxproj
  Zipadoo/Zipadoo/Info.plist
Labels: Fix, 여훈

#400 내주변 장소 검색 기능 구현
  Zipadoo/Zipadoo.xcodeproj/project.pbxproj
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/NewMapViews/AddPlaceButtonCell.swift
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/NewMapViews/SearchbarCell.swift
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/OneAddLocation.swift
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/OneMapView.swift
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/PreviewPlaceOnMap.swift
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/SearchInKakaoLocal.swift
  Zipadoo/Zipadoo/Views/Home/AddPromise/AddPromiseView.swift
  Zipadoo/Zipadoo/Views/Home/PromiseEditView.swift
Labels: Feat, Fix, 상규, Home

#402 프로필 수정 버튼 비활성화 오류 해결
  Zipadoo/Zipadoo.xcodeproj/project.pbxproj
  Zipadoo/Zipadoo/Views/MyPageViews/EditProfilView.swift
Labels: Fix, 해수

#404 온보딩 페이지, TipKit 추가
  Zipadoo/Zipadoo.xcodeproj/project.pbxproj
  Zipadoo/Zipadoo/Assets.xcassets/Onboard/Contents.json
  Zipadoo/Zipadoo/Assets.xcassets/Onboard/SC 44.imageset/Contents.json
  Zipadoo/Zipadoo/Assets.xcassets/Onboard/SC 44.imageset/SC 44.png
  Zipadoo/Zipadoo/Assets.xcassets/Onboard/SC 45.imageset/Contents.json
  Zipadoo/Zipadoo/Assets.xcassets/Onboard/SC 45.imageset/SC 45.png
  Zipadoo/Zipadoo/Assets.xcassets/Onboard/SC 48.imageset/Contents.json
  Zipadoo/Zipadoo/Assets.xcassets/Onboard/SC 48.imageset/SC 48.png
  Zipadoo/Zipadoo/Tip.swift
  Zipadoo/Zipadoo/Views/ContentView.swift
  Zipadoo/Zipadoo/Views/Friends/FriendsView.swift
  Zipadoo/Zipadoo/Views/Home/HomeMainView.swift
  Zipadoo/Zipadoo/Views/LaunchScreen.swift
  Zipadoo/Zipadoo/Views/Login/LoginView.swift
  Zipadoo/Zipadoo/Views/OnboardingViews/OnboardingLastPageView.swift
  Zipadoo/Zipadoo/Views/OnboardingViews/OnboardingPageTabView.swift
  Zipadoo/Zipadoo/Views/OnboardingViews/OnboardingPageView.swift
  Zipadoo/Zipadoo/ZipadooApp.swift
Labels: Fix, 여훈

#406 회원가입 시 에러 발생 현상 조치
  Zipadoo/Zipadoo/Views/MyPageViews/MyPageView.swift
Labels: Fix, 해수

#407 [FIX] 약속 디테일뷰 디자인 수정
  Zipadoo/Zipadoo/Assets.xcassets/colors/primary2.colorset/Contents.json
  Zipadoo/Zipadoo/Extention/Extention.swift
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/NewMapViews/SearchbarCell.swift
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/SearchInKakaoLocal.swift
  Zipadoo/Zipadoo/Views/Home/PromiseDetailView.swift
  Zipadoo/Zipadoo/Views/Home/PromiseEditView.swift
Labels: Fix, Design, 상규, Home

#408 [FIX]온보딩 페이지 수정
  Zipadoo/Zipadoo/Views/OnboardingViews/OnboardingPageView.swift
Labels: Fix, 여훈

#414 [FIX] 도착 위치 반경
  Zipadoo/Zipadoo/Views/Home/PromiseDetailMapView.swift
Labels: Fix, 여훈, Home

#415 [REAFCTOR] 알람 한번만 오도록 해결
  Zipadoo/Zipadoo.xcodeproj/project.pbxproj
  Zipadoo/Zipadoo/ViewModels/PromiseViewModel.swift
Labels: Fix, Refactor, 현정, Push

#416 [FIX] 도착 메세지 뷰 다크모드 적용 #409
  Zipadoo/Zipadoo.xcodeproj/project.pbxproj
  Zipadoo/Zipadoo/Views/Alert/ArrivalMessagingView.swift
Labels: Fix, 해수

#417 위치정보, 지도뷰 관련 피드백 반영
  Zipadoo/Zipadoo.xcodeproj/project.pbxproj
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/NewMapViews/SearchbarCell.swift
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/OneAddLocation.swift
  Zipadoo/Zipadoo/Views/Home/AddPomisePlaceSubViews/OneMapView.swift
  Zipadoo/Zipadoo/Views/Home/AddPromise/AddPromiseView.swift
  Zipadoo/Zipadoo/Views/Home/PromiseDetailMapView.swift
  Zipadoo/Zipadoo/Views/Home/PromiseDetailView.swift
Labels: Fix, 상규, Home
